# Aula 02 - Python

## Dados numéricos

In [3]:
# Variável inteira
a=1
print('Valor de a = '+str(a))
type(a)

Valor de a = 1


int

In [4]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)

1.0


float

In [5]:
# Converter float para int
c = int(b)
print(c)
type(c)

1


int

In [6]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [7]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


## Dados de texto

In [8]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


## Dados tipo bool - lógica

In [9]:
a == 1

True

In [10]:
h = (a==1)
print(h)
type(h)

True


bool

In [11]:
h = (a==2)
print(h)
type(h)

False


bool

In [12]:
i = True
type(i)

bool

In [13]:
ii = 'True'
type(ii)

str

### Operação de comparação

In [14]:
# Operação ==
a==b

True

In [15]:
# Operação ><
a>b

False

In [16]:

# Operação !=
a!=b

False

In [17]:
# Operação >= ou <=
a>=b

True

## Operações matemáticas

In [19]:
# Soma 
a+b

2.0

In [20]:
# Soma e atribui valor
ab = a+b
print(ab)

2.0


In [21]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [22]:
# Divisão
a/b

1.0

In [23]:
# Potencia
5**2

25

In [ ]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(10)

In [27]:

math.exp(0)

1.0

In [28]:
math.exp(a)

2.718281828459045

In [29]:
math.exp(-10)

4.5399929762484854e-05

In [30]:
import math as mt
mt.log(c)

0.0

In [31]:
mt.log10(100)

2.0

## Listas

In [32]:
myFirstList = [1,2,3]
print(myFirstList)

[1, 2, 3]


In [33]:
# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])

1
3


In [34]:
myFirstList==a

False

In [35]:
myFirstList[0]==a

True

In [36]:
mySecList = [1,a,'c']
print(mySecList)

[1, 1, 'c']


In [37]:
type(mySecList)

list

In [38]:

type(mySecList[2])

str

In [39]:
type(mySecList[1])

int

## Caminhos = path

In [56]:
path = r"C:\Users\cecil\OneDrive\Documentos\CPA\ENS5173"
print(path)

C:\Users\cecil\OneDrive\Documentos\CPA\ENS5173


In [57]:
path = "C:/Users/cecil/OneDrive/Documentos/CPA/ENS5173"
print(path)

C:/Users/cecil/OneDrive/Documentos/CPA/ENS5173


In [58]:
import os
# Listar arquivos na pasta
os.listdir(path)

['.git', '.gitignore', 'inputs', 'README.md', 'scripts', 'venv']

In [59]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [60]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:/Users/cecil/OneDrive/Documentos/CPA/ENS5173/.git'

In [61]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [62]:
# Diretório que estou trababalhando
os.getcwd()

'C:\\Users\\cecil\\OneDrive\\Documentos\\CPA\\ENS5173\\venv\\Scripts'

In [63]:
# Mudo de diretório para o caminho 
os.chdir('C:\\Users\\cecil\\OneDrive\\Documentos\\')

In [64]:
os.getcwd()

'C:\\Users\\cecil\\OneDrive\\Documentos'

In [65]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Criando diretório C:\Users\cecil\OneDrive\Documentos/test


In [66]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretório C:\Users\cecil\OneDrive\Documentos/test2


## Numpy arrays e Pandas DataFrames

In [67]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [68]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [69]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)

[[0.2561451  0.62755133 0.52630437 0.01008624 0.34654406 0.06520685
  0.18134111 0.73174331 0.75343034 0.78890579]
 [0.08234571 0.83472299 0.58327763 0.80206784 0.47055422 0.18636403
  0.04754455 0.28989725 0.30875631 0.09763786]
 [0.4084331  0.426584   0.40514953 0.01587114 0.1366075  0.98744338
  0.8165335  0.68858395 0.05130533 0.28430376]
 [0.12068655 0.6857641  0.97768338 0.25215657 0.67084944 0.77831466
  0.43160951 0.26139765 0.36597311 0.26099018]
 [0.41747217 0.56076062 0.99045947 0.9131939  0.20190701 0.35894223
  0.88377376 0.11895139 0.0194723  0.94916357]
 [0.05306836 0.45139472 0.69488594 0.05592343 0.56811881 0.76175935
  0.21640782 0.74085489 0.05088133 0.89207368]
 [0.88141277 0.6720588  0.35955883 0.20165299 0.90915676 0.2468128
  0.60885605 0.50706652 0.437315   0.22156368]
 [0.37736275 0.26589749 0.9823795  0.44371202 0.69045032 0.91260897
  0.85680469 0.58841927 0.58019595 0.02866466]
 [0.1126492  0.7978834  0.29194974 0.79213566 0.7733916  0.16370909
  0.79569154 

In [70]:
# Acessando valores da matriz
n[0,:]

array([0.2561451 , 0.62755133, 0.52630437, 0.01008624, 0.34654406,
       0.06520685, 0.18134111, 0.73174331, 0.75343034, 0.78890579])

In [71]:
n[:,0]

array([0.2561451 , 0.08234571, 0.4084331 , 0.12068655, 0.41747217,
       0.05306836, 0.88141277, 0.37736275, 0.1126492 , 0.61952807])

In [72]:
n[:,1:5]

array([[0.62755133, 0.52630437, 0.01008624, 0.34654406],
       [0.83472299, 0.58327763, 0.80206784, 0.47055422],
       [0.426584  , 0.40514953, 0.01587114, 0.1366075 ],
       [0.6857641 , 0.97768338, 0.25215657, 0.67084944],
       [0.56076062, 0.99045947, 0.9131939 , 0.20190701],
       [0.45139472, 0.69488594, 0.05592343, 0.56811881],
       [0.6720588 , 0.35955883, 0.20165299, 0.90915676],
       [0.26589749, 0.9823795 , 0.44371202, 0.69045032],
       [0.7978834 , 0.29194974, 0.79213566, 0.7733916 ],
       [0.35310336, 0.9237586 , 0.09858886, 0.43738654]])

In [73]:
n[0,1:5]

array([0.62755133, 0.52630437, 0.01008624, 0.34654406])

In [75]:
n[0,-1]

0.7889057910631668

In [76]:
n[0,4:-1]

array([0.34654406, 0.06520685, 0.18134111, 0.73174331, 0.75343034])

In [77]:
n[0,4:]

array([0.34654406, 0.06520685, 0.18134111, 0.73174331, 0.75343034,
       0.78890579])

In [78]:
an = np.log(n*5)
print(an)

[[ 0.24742671  1.1435081   0.96756232 -2.98714525  0.54969259 -1.12075281
  -0.09793753  1.29711241  1.32631919  1.37232954]
 [-0.88739096  1.42878256  1.07034592  1.38887583  0.85559382 -0.07061544
  -1.43665013  0.37120918  0.43423494 -0.71705208]
 [ 0.71401075  0.75749192  0.70593884 -2.53381483 -0.38120555  1.59680179
   1.40675058  1.23631987 -1.36052271  0.35172587]
 [-0.50512066  1.23221633  1.58686851  0.23173282  1.21022737  1.35881352
   0.7692039   0.26772544  0.60424248  0.26616542]
 [ 0.73590051  1.03097675  1.59985158  1.51863087  0.00948988  0.5848441
   1.48588374 -0.51960245 -2.32932446  1.55726377]
 [-1.32673652  0.8140248   1.24543035 -1.27433387  1.0440132   1.33731333
   0.07884733  1.30948741 -1.36882133  1.49523136]
 [ 1.48320867  1.21202847  0.58656045  0.00823097  1.51420017  0.21031281
   1.1132645   0.93032483  0.78233639  0.10239269]
 [ 0.63488956  0.2847935   1.59166033  0.79685838  1.23902666  1.51799013
   1.45489262  1.07912237  1.06504853 -1.94265247]
 